-- MySQL Script generated by MySQL Workbench
-- Tue Aug 26 10:54:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema historico_fichas_subidas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema historico_fichas_subidas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `historico_fichas_subidas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `historico_fichas_subidas` ;

-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`ccaa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`ccaa` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo_ine` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_ccaa_nombre` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `codigo_ine` (`codigo_ine` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`enlaces_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`enlaces_base` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `base_url` VARCHAR(255) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_enlaces_base_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`provincias` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ccaa_id` SMALLINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo_ine` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_prov_nombre` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `uq_prov_ine` (`codigo_ine` ASC) VISIBLE,
  INDEX `ix_prov_ccaa` (`ccaa_id` ASC) VISIBLE,
  CONSTRAINT `fk_prov_ccaa`
    FOREIGN KEY (`ccaa_id`)
    REFERENCES `historico_fichas_subidas`.`ccaa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`fichas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`fichas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_ficha_subida` DECIMAL(20,0) NOT NULL,
  `nombre_ficha` VARCHAR(200) NOT NULL,
  `nombre_slug` VARCHAR(220) NULL DEFAULT NULL,
  `vencimiento` DATE NULL DEFAULT NULL,
  `fecha_redaccion` DATE NULL DEFAULT NULL,
  `fecha_subida_web` DATE NULL DEFAULT NULL,
  `trabajador_id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `trabajador_subida_id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ambito_nivel` ENUM('UE', 'ESTADO', 'CCAA', 'PROVINCIA') NOT NULL,
  `ambito_ccaa_id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ambito_provincia_id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ambito_municipal` VARCHAR(150) NULL DEFAULT NULL,
  `tramite_tipo` ENUM('no', 'si', 'directo') NULL DEFAULT NULL,
  `complejidad` ENUM('baja', 'media', 'alta') NULL DEFAULT NULL,
  `complejidad_peso` TINYINT GENERATED ALWAYS AS ((case `complejidad` when _utf8mb4'baja' then 1 when _utf8mb4'media' then 2 when _utf8mb4'alta' then 3 else NULL end)) STORED,
  `enlace_base_id` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  `enlace_seg_override` VARCHAR(120) NULL DEFAULT NULL,
  `frase_publicitaria` VARCHAR(300) NULL DEFAULT NULL,
  `texto_divulgacion` TEXT NULL DEFAULT NULL,
  `existe_frase` TINYINT(1) GENERATED ALWAYS AS ((case when ((`frase_publicitaria` is not null) and (regexp_replace(`frase_publicitaria`,_utf8mb4'\\s+',_cp850'') <> _utf8mb4'')) then 1 else 0 end)) STORED,
  `destaque_principal` ENUM('novedad', 'destacable') NULL DEFAULT NULL,
  `destaque_secundario` ENUM('novedad', 'destacable') NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_fichas_id_ficha_subida` (`id_ficha_subida` ASC) VISIBLE,
  UNIQUE INDEX `uq_fichas_nombre_slug` (`nombre_slug` ASC) VISIBLE,
  INDEX `ix_fichas_vencimiento` (`vencimiento` ASC) VISIBLE,
  INDEX `ix_fichas_fecha_redaccion` (`fecha_redaccion` ASC) VISIBLE,
  INDEX `ix_fichas_fecha_subida_web` (`fecha_subida_web` ASC) VISIBLE,
  INDEX `ix_fichas_trabajador` (`trabajador_id` ASC) VISIBLE,
  INDEX `ix_fichas_trabajador_subida` (`trabajador_subida_id` ASC) VISIBLE,
  INDEX `ix_fichas_ambito_nivel` (`ambito_nivel` ASC) VISIBLE,
  INDEX `ix_fichas_ccaa` (`ambito_ccaa_id` ASC) VISIBLE,
  INDEX `ix_fichas_provincia` (`ambito_provincia_id` ASC) VISIBLE,
  INDEX `ix_fichas_tramite_tipo` (`tramite_tipo` ASC) VISIBLE,
  INDEX `ix_fichas_complejidad` (`complejidad` ASC) VISIBLE,
  INDEX `ix_fichas_complejidad_peso` (`complejidad_peso` ASC) VISIBLE,
  INDEX `ix_fichas_enlace_base` (`enlace_base_id` ASC) VISIBLE,
  FULLTEXT INDEX `ft_fichas_nombre` (`nombre_ficha`) VISIBLE,
  FULLTEXT INDEX `ft_fichas_frase` (`frase_publicitaria`) VISIBLE,
  FULLTEXT INDEX `ft_fichas_texto` (`texto_divulgacion`) VISIBLE,
  CONSTRAINT `fk_fichas_ccaa`
    FOREIGN KEY (`ambito_ccaa_id`)
    REFERENCES `historico_fichas_subidas`.`ccaa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_fichas_provincia`
    FOREIGN KEY (`ambito_provincia_id`)
    REFERENCES `historico_fichas_subidas`.`provincias` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`portales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`portales` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_portales_slug` (`slug` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`ficha_portal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`ficha_portal` (
  `ficha_id` BIGINT UNSIGNED NOT NULL,
  `portal_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ficha_id`, `portal_id`),
  INDEX `ix_fp_portal` (`portal_id` ASC) VISIBLE,
  CONSTRAINT `fk_fp_ficha`
    FOREIGN KEY (`ficha_id`)
    REFERENCES `historico_fichas_subidas`.`fichas` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_fp_portal`
    FOREIGN KEY (`portal_id`)
    REFERENCES `historico_fichas_subidas`.`portales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`tematicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`tematicas` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(64) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_tema_slug` (`slug` ASC) VISIBLE,
  UNIQUE INDEX `uq_tema_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`ficha_tematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`ficha_tematica` (
  `ficha_id` BIGINT UNSIGNED NOT NULL,
  `tematica_id` SMALLINT UNSIGNED NOT NULL,
  `orden` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`ficha_id`, `tematica_id`),
  INDEX `ix_ft_tematica` (`tematica_id` ASC) VISIBLE,
  INDEX `ix_ft_orden` (`orden` ASC) VISIBLE,
  CONSTRAINT `fk_ft_ficha`
    FOREIGN KEY (`ficha_id`)
    REFERENCES `historico_fichas_subidas`.`fichas` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_ft_tema`
    FOREIGN KEY (`tematica_id`)
    REFERENCES `historico_fichas_subidas`.`tematicas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `historico_fichas_subidas`.`trabajadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`trabajadores` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(64) NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_trab_slug` (`slug` ASC) VISIBLE,
  INDEX `ix_trab_activo` (`activo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `historico_fichas_subidas` ;

-- -----------------------------------------------------
-- Placeholder table for view `historico_fichas_subidas`.`v_fichas_enlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historico_fichas_subidas`.`v_fichas_enlace` (`id` INT, `id_ficha_subida` INT, `nombre_ficha` INT, `nombre_slug` INT, `vencimiento` INT, `fecha_redaccion` INT, `fecha_subida_web` INT, `trabajador_id` INT, `trabajador_subida_id` INT, `ambito_nivel` INT, `ambito_ccaa_id` INT, `ambito_provincia_id` INT, `ambito_municipal` INT, `tramite_tipo` INT, `complejidad` INT, `complejidad_peso` INT, `enlace_base_id` INT, `enlace_seg_override` INT, `frase_publicitaria` INT, `texto_divulgacion` INT, `existe_frase` INT, `destaque_principal` INT, `destaque_secundario` INT, `created_at` INT, `updated_at` INT, `enlace_web` INT);

-- -----------------------------------------------------
-- View `historico_fichas_subidas`.`v_fichas_enlace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `historico_fichas_subidas`.`v_fichas_enlace`;
USE `historico_fichas_subidas`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`georgi`@`%` SQL SECURITY DEFINER VIEW `historico_fichas_subidas`.`v_fichas_enlace` AS select `f`.`id` AS `id`,`f`.`id_ficha_subida` AS `id_ficha_subida`,`f`.`nombre_ficha` AS `nombre_ficha`,`f`.`nombre_slug` AS `nombre_slug`,`f`.`vencimiento` AS `vencimiento`,`f`.`fecha_redaccion` AS `fecha_redaccion`,`f`.`fecha_subida_web` AS `fecha_subida_web`,`f`.`trabajador_id` AS `trabajador_id`,`f`.`trabajador_subida_id` AS `trabajador_subida_id`,`f`.`ambito_nivel` AS `ambito_nivel`,`f`.`ambito_ccaa_id` AS `ambito_ccaa_id`,`f`.`ambito_provincia_id` AS `ambito_provincia_id`,`f`.`ambito_municipal` AS `ambito_municipal`,`f`.`tramite_tipo` AS `tramite_tipo`,`f`.`complejidad` AS `complejidad`,`f`.`complejidad_peso` AS `complejidad_peso`,`f`.`enlace_base_id` AS `enlace_base_id`,`f`.`enlace_seg_override` AS `enlace_seg_override`,`f`.`frase_publicitaria` AS `frase_publicitaria`,`f`.`texto_divulgacion` AS `texto_divulgacion`,`f`.`existe_frase` AS `existe_frase`,`f`.`destaque_principal` AS `destaque_principal`,`f`.`destaque_secundario` AS `destaque_secundario`,`f`.`created_at` AS `created_at`,`f`.`updated_at` AS `updated_at`,concat(`eb`.`base_url`,coalesce(`f`.`enlace_seg_override`,convert(cast(`f`.`id_ficha_subida` as char charset cp850) using utf8mb4))) AS `enlace_web` from (`historico_fichas_subidas`.`fichas` `f` join `historico_fichas_subidas`.`enlaces_base` `eb` on((`eb`.`id` = `f`.`enlace_base_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
